### PR TITLE
fix uninitialized constant Chef::Knife::Cloud::VraServerCreate::VraServiceHelpers

### LINKED ISSUE #53: knife vra <command> fails
### Versions

* Version of knife-vrealize: 6.0.0
* Version of chef: 
Chef Workstation version: 20.9.136
Chef Infra Client version: 16.4.41
Chef InSpec version: 4.22.22
Chef CLI version: 3.0.27
Chef Habitat version: 1.6.56
Test Kitchen version: 2.6.0
Cookstyle version: 6.16.10

### Platform Details

* Version of vRA: Version: 7.5.0 (Build: 10053500)
* Version of vRO: n/a
* Version of ESXi: n/a

### Scenario
Get info from the vRA API using knife

### Steps to Reproduce
Run `chef shell-init powershell | invoke-expression`
Install the gem with `chef gem install knife-vrealize`
Run any `knife vra` command: `knife vra server create`, `knife vra catalog list` etc

### Expected Result
get the expected result of the commands - a server is spun up, the list is returned, etc

### Actual Result
Fatal errors. 
One thing i notice is that the gem itself appears to be coming from `C:/Users/mcascone1/AppData/Local/chefdk/gem/ruby/2.7.0/gems/`. Is that correct? I thought that by using `chef gem install` and/or `chef shell-init powershell` they'd be put in the right place.

Fatal errors:
```powershell
~\Documents\github> knife vra catalog list --entitled
Traceback (most recent call last):
        16: from C:/opscode/chef-workstation/bin/knife:370:in `<main>'
        15: from C:/opscode/chef-workstation/bin/knife:370:in `load'
        14: from C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/chef-16.4.41-universal-mingw32/bin/knife:24:in `<top (required)>'
        13: from C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/chef-16.4.41-universal-mingw32/lib/chef/application/knife.rb:163:in `run'
        12: from C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/chef-16.4.41-universal-mingw32/lib/chef/knife.rb:224:in `run'
        11: from C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/chef-16.4.41-universal-mingw32/lib/chef/knife.rb:161:in `subcommand_class_from'
        10: from C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/chef-16.4.41-universal-mingw32/lib/chef/knife/core/subcommand_loader.rb:129:in `command_class_from'
         9: from C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/chef-16.4.41-universal-mingw32/lib/chef/knife/core/subcommand_loader.rb:115:in `load_command'
         8: from C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/chef-16.4.41-universal-mingw32/lib/chef/knife/core/subcommand_loader.rb:105:in `load_commands'
         7: from C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/chef-16.4.41-universal-mingw32/lib/chef/knife/core/subcommand_loader.rb:105:in `each'
         6: from C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/chef-16.4.41-universal-mingw32/lib/chef/knife/core/subcommand_loader.rb:105:in `block in load_commands'
         5: from C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/chef-16.4.41-universal-mingw32/lib/chef/knife/core/subcommand_loader.rb:105:in `load'
         4: from C:/Users/mcascone1/AppData/Local/chefdk/gem/ruby/2.7.0/gems/knife-vrealize-6.0.0/lib/chef/knife/vra_server_create.rb:26:in `<top (required)>'
         3: from C:/Users/mcascone1/AppData/Local/chefdk/gem/ruby/2.7.0/gems/knife-vrealize-6.0.0/lib/chef/knife/vra_server_create.rb:27:in `<class:Chef>'
         2: from C:/Users/mcascone1/AppData/Local/chefdk/gem/ruby/2.7.0/gems/knife-vrealize-6.0.0/lib/chef/knife/vra_server_create.rb:28:in `<class:Knife>'
         1: from C:/Users/mcascone1/AppData/Local/chefdk/gem/ruby/2.7.0/gems/knife-vrealize-6.0.0/lib/chef/knife/vra_server_create.rb:29:in `<class:Cloud>'
C:/Users/mcascone1/AppData/Local/chefdk/gem/ruby/2.7.0/gems/knife-vrealize-6.0.0/lib/chef/knife/vra_server_create.rb:30:in `<class:VraServerCreate>': uninitialized constant Chef::Knife::Cloud::VraServerCreate::VraServiceHelpers (NameError)
Did you mean?  Chef::Knife::Cloud::VraServiceOptions
```

```
~\Documents\github> knife vra server create $catitem
Traceback (most recent call last):
        16: from C:/opscode/chef-workstation/bin/knife:370:in `<main>'
        15: from C:/opscode/chef-workstation/bin/knife:370:in `load'
        14: from C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/chef-16.4.41-universal-mingw32/bin/knife:24:in `<top (required)>'
        13: from C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/chef-16.4.41-universal-mingw32/lib/chef/application/knife.rb:163:in `run'
        12: from C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/chef-16.4.41-universal-mingw32/lib/chef/knife.rb:224:in `run'
        11: from C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/chef-16.4.41-universal-mingw32/lib/chef/knife.rb:161:in `subcommand_class_from'
        10: from C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/chef-16.4.41-universal-mingw32/lib/chef/knife/core/subcommand_loader.rb:129:in `command_class_from'
         9: from C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/chef-16.4.41-universal-mingw32/lib/chef/knife/core/subcommand_loader.rb:115:in `load_command'
         8: from C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/chef-16.4.41-universal-mingw32/lib/chef/knife/core/subcommand_loader.rb:105:in `load_commands'
         7: from C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/chef-16.4.41-universal-mingw32/lib/chef/knife/core/subcommand_loader.rb:105:in `each'
         6: from C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/chef-16.4.41-universal-mingw32/lib/chef/knife/core/subcommand_loader.rb:105:in `block in load_commands'
         5: from C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/chef-16.4.41-universal-mingw32/lib/chef/knife/core/subcommand_loader.rb:105:in `load'
         4: from C:/Users/mcascone1/AppData/Local/chefdk/gem/ruby/2.7.0/gems/knife-vrealize-6.0.0/lib/chef/knife/vra_server_create.rb:26:in `<top (required)>'
         3: from C:/Users/mcascone1/AppData/Local/chefdk/gem/ruby/2.7.0/gems/knife-vrealize-6.0.0/lib/chef/knife/vra_server_create.rb:27:in `<class:Chef>'
         2: from C:/Users/mcascone1/AppData/Local/chefdk/gem/ruby/2.7.0/gems/knife-vrealize-6.0.0/lib/chef/knife/vra_server_create.rb:28:in `<class:Knife>'
         1: from C:/Users/mcascone1/AppData/Local/chefdk/gem/ruby/2.7.0/gems/knife-vrealize-6.0.0/lib/chef/knife/vra_server_create.rb:29:in `<class:Cloud>'
C:/Users/mcascone1/AppData/Local/chefdk/gem/ruby/2.7.0/gems/knife-vrealize-6.0.0/lib/chef/knife/vra_server_create.rb:30:in `<class:VraServerCreate>': uninitialized constant Chef::Knife::Cloud::VraServerCreate::VraServiceHelpers (NameError)
Did you mean?  Chef::Knife::Cloud::VraServiceOptions
```

### PR DESCRIPTION
**Pull request by mwrock**
fixes #53

Signed-off-by: mwrock <matt@mattwrock.com>

### CODE REVIEW

**Review by phiggins — APPROVED** [review]

File: lib/chef/knife/vra_server_create.rb [hunk 1]
```diff
@@ -22,20 +22,20 @@
...
+require_relative "cloud/vra_service_helpers"
 
 class Chef
   class Knife
     class Cloud
       class VraServerCreate < ServerCreateCommand
-        include VraServiceHelpers
         include VraServiceOptions
         include ServerCreateOptions
+        include VraServiceHelpers
```
Comment (tas50) [inline lib/chef/knife/vra_server_create.rb:33]: If you can make it work by putting the require and the include in the deps block you won't take the penalty of loading that code every time you run any old knife command.

Comment (mwrock) [reply lib/chef/knife/vra_server_create.rb:33]: That was my first attempt but it blew up several tests that call `validate_params!` directly which does not trigger the `deps` block.
